{{- range $component := list "backend" "frontend" }}
{{- $c := index $.Values $component }}
{{- if $c.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" (include "heimdall.fullname" $) $component }}
  labels:
    {{- include "heimdall.componentLabels" (dict "ctx" $ "component" $component) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" (include "heimdall.fullname" $) $component }}
  minReplicas: {{ $c.autoscaling.minReplicas }}
  maxReplicas: {{ $c.autoscaling.maxReplicas }}
  metrics:
    {{- with $c.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
    {{- with $c.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
{{- end }}
{{- end }}
