{{- if .Values.ingress.enabled }}
{{- $svcName := include "heimdall.frontend.fullname" . }}
{{- $svcPort := .Values.frontend.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.componentLabels" (dict "ctx" . "component" "frontend") | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- range . }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - {{- with .host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
