{{- if and (not .Values.gitlab.existingSecret) .Values.gitlab.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.componentLabels" (dict "ctx" . "component" "backend") | nindent 4 }}
type: Opaque
data:
  GITLAB_TOKEN: {{ .Values.gitlab.token | b64enc | quote }}
{{- end }}
